---
# stages that can be used by jobs and is defined globally
stages:
  - test
  - build

# `stage` allows to group jobs into different stages,
# and jobs of the same stage are executed in parallel
format:
  stage: test
  image: golangci/golangci-lint:latest
  script:
    - cd hello-server && golangci-lint run --enable-all

kubeval:
  stage: test
  image:
    name: garethr/kubeval
    entrypoint: ["/bin/sh"]
  script:
    - /kubeval -d k1s

build:
  image: docker:latest
  stage: build
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker info
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - cd hello-server && docker build -t registry.gitlab.com/1995parham/k1s/hello-server:latest .
  after_script:
    - docker push registry.gitlab.com/1995parham/k1s/hello-server:latest
  only:
    changes:
      - hello-server/*
