---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k1s
  labels:
    app: k1s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k1s
  template:
    metadata:
      labels:
        app: k1s
    spec:
      containers:
        - name: hello-server
          image: docker.pkg.github.com/1995parham/k1s/hello-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1372
          livenessProbe:
            httpGet:
              path: /healthz
              port: 1372
            initialDelaySeconds: 3
            periodSeconds: 3
