---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k1s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k1s
  template:
    metadata:
      labels:
        app: k1s
    spec:
      containers:
        - name: hello-server
          image: ghcr.io/1995parham/k1s:main
          ports:
            - containerPort: 1378
