name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build hello-server/ --file hello-server/Dockerfile --tag docker.pkg.github.com/1995parham/k1s/hello-server:latest
    - name: Push the Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        docker push docker.pkg.github.com/1995parham/k1s/hello-server:latest
